# This beginner-level config uses the GPU (gpuID: 0) to compress video
# using ffmpeg's H265 codec

# Before a recording make sure that the PC's clock is synced and the RTC-IOT relay are synced.

# Run campy to acquire video pointing to the config file: campy-acquire .\configs\campy_config_1cam_flir_gpu_h265_wheat.yaml

# Recording parameters
#videoFolder: "./videos"
#videoFilename: "0.mp4"
#videoFolder: "./experimental_videos/FINALTEST_BEFORE-EXP/"
#videoFilename: "FINALTEST_BEFORE-EXP.mp4"
#frameRate: 60

# Experimental Recording paramters
videoFolder: "./experimental_videos/reps/DD-wheat/agesync_8-7-26-rep1-DD/"
videoFilename: "DD-wheat_agesync_8-7-26-rep1-DD.mp4"
frameRate: 60

# Testing recording times
#recTimeInSec: 600
#chunkLengthInSec: 60

# Recording Times for experiments 24h 
#recTimeInSec: 86400 # 24h
#chunkLengthInSec: 3600 # 1h chunks

# Recording Times for 96h exp
recTimeInSec: 345600
chunkLengthInSec: 3600 


# Camera parameters
numCams: 1
cameraMake: "flir"
frameWidth: 2048
frameHeight: 1536
pixelFormatInput: "gray" # "bayer_rggb8" # 
pixelFormatOutput: "rgb0"

# Flir settings
cameraSettings: "UserSet1"
#cameraTrigger: "Line3"
bufferSize: 200
cameraExposureTimeInUs: 3001
# higher gain due to less brightness with wheat...
cameraGain: 6.6
disableGamma: True # False 
#disableGamma: False
# Bug with gamma, when gamma is enabled the file size is significantly higher
#gammaLevel: 1.3
cameraDebug: True # True # 


# Compression parameters
gpuID: 0                            
gpuMake: "nvidia" # "intel" # "amd"         # "nvidia", "amd", "intel"                  
codec: "h265"                         # "h264", "h265", "av1", or user-defined video codec
#quality: 29 # around 6gb per 24h
#quality: 26 # aroung 44gb per 24h
quality: 27 # around 18gb per 24h
preset: "slow"                       
ffmpegLogLevel: "info"               # "quiet", "warning", "info"
# ffmpegPath: "C:/Code/ffmpeg"       # Location of ffmpeg binary if not using Anaconda


# Display parameters
displayFrameCounter: 1
displayFrameRate: 10

# Trigger Parameters
#startArduino: True
#serialPort: "COM3"                    # e.g. "COM3" Win; "/dev/ttyACM0" Linux
#digitalPins: [0,1,2]
